language: node_js
node_js:
  - '9'
branches:
  only:
  - master
  - gh-pages
script: npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: gh-pages
