language: node_js
node_js:
  - '9'
before_install:
  - npm i -g npm@^6.0.0
branches:
  only:
  - master
  - gh-pages
script: npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  target_branch: gh-pages
  on:
    branch: master
