language: node_js
node_js:
  - '9'
before_install:
  - npm i -g npm@5.6.0
branches:
  only:
  - master
script: npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: gh-pages
